"""One-shot session verdict, generated by a single grounded Gemini call.

Rendered as a panel between the video cards and the chat: "what's the
headline comparison?" so the user has an immediate take before they ask
anything. Subsequent chat turns go deeper.

The call is grounded with Google Search so the model can pull in
world-context for time-sensitive topics (a politics video benefiting
from a current news cycle, a topic that's spiking in search interest,
etc.). The cited web pages are returned alongside the verdict so the
frontend can render a "From the web" section in the same panel.

Cached per-session: regenerating costs a Gemini call + ~2-4s of latency,
so we hold the result in process memory until the session expires (or
until ?refresh=1 is passed). The cache is in-memory only; on Cloud Run
restart the next request just regenerates.
"""

from __future__ import annotations

import logging
import re
import threading
from typing import Iterable

from langchain_core.messages import HumanMessage, SystemMessage

from app import sessions
from app.config import settings
from app.models import Verdict, VideoMeta, VideoSlot, WebSource
from langchain_google_genai import ChatGoogleGenerativeAI
from app.rag.vector_store import list_chunks

log = logging.getLogger(__name__)

# session_id -> Verdict
_cache: dict[str, Verdict] = {}
_lock = threading.Lock()


# ---------- Prompt --------------------------------------------------------

_SYSTEM = """You are a sharp content strategist. The user shows you two
short-form videos and you give a single skim-readable verdict for them.

You have Google Search. Use it ONLY when one of the videos is on a
clearly time-sensitive topic (politics, sports outcomes, exam results,
breaking news, market moves, viral cultural moments). Skip search for
evergreen topics (cooking, programming basics, generic advice, fitness).

Respond in EXACTLY this format. No markdown. No headers other than the
labels below. No bullets except after REASONS.

TOPIC_A: <Video A's topic in 2 to 5 words. e.g. "Engineering & entrepreneurship" or "Ukraine ceasefire">
TOPIC_B: <Video B's topic in 2 to 5 words.>
WINNING_VIDEO: A
OPINION: <one or two short sentences in plain English. If a topic is in the news right now, lead with that. e.g. "Video A is winning because the Ukraine ceasefire just hit headlines today and people are searching for explanations.">
REASONS:
- <reason 1: short, concrete, plain English>
- <reason 2: same>
- <reason 3: optional>

Rules:
- TOPIC_A and TOPIC_B describe ONLY their respective video. They can be
  completely different topics -- that is normal.
- Use simple words. Short sentences. No jargon, no "leverages", no "manifests".
- WINNING_VIDEO must be exactly "A", "B", or "TIE".
- 2 or 3 REASONS. No more.
- Do NOT use markdown asterisks, headers, or numbered lists.
"""


def _format_meta(meta: VideoMeta) -> str:
    return (
        f"  creator: @{meta.creator} ({_fmt_int(meta.follower_count)} followers)\n"
        f"  views: {_fmt_int(meta.views)} | likes: {_fmt_int(meta.likes)} | comments: {_fmt_int(meta.comments)}\n"
        f"  engagement_rate: {meta.engagement_rate:.2f}% | view_velocity: {_fmt_velocity(meta.view_velocity)} | life_stage: {meta.life_stage or '?'}\n"
        f"  hashtags: {', '.join(meta.hashtags[:8]) or '(none)'}\n"
        f"  topic_keywords: {', '.join(meta.topic_keywords) or '(none)'}\n"
        f"  age_days: {meta.age_days if meta.age_days is not None else '?'}\n"
    )


def _fmt_int(n: int | None) -> str:
    return f"{n:,}" if isinstance(n, int) else "?"


def _fmt_velocity(v: float | None) -> str:
    return f"{v:,.0f}/day" if v is not None else "?"


def _hook_text(session_id: str, slot: VideoSlot) -> str:
    """First transcript chunk = the hook (chunk_idx 0)."""
    chunks = list_chunks(session_id, video_slot=slot, kind="transcript", limit=2)
    if not chunks:
        return "(no transcript)"
    return (chunks[0].get("text") or "").strip()[:600]


def _build_user_prompt(meta_a: VideoMeta, meta_b: VideoMeta, hook_a: str, hook_b: str) -> str:
    return (
        "VIDEO A:\n"
        f"{_format_meta(meta_a)}"
        f"  hook: {hook_a!r}\n\n"
        "VIDEO B:\n"
        f"{_format_meta(meta_b)}"
        f"  hook: {hook_b!r}\n\n"
        "Now give the verdict in the exact format from the system prompt."
    )


# ---------- Parsing -------------------------------------------------------

_LABEL_RE = re.compile(r"^\s*([A-Z_]+)\s*:\s*(.*)$")


def _parse_response(
    text: str,
) -> tuple[str, str, str, VideoSlot | None, str, list[str]]:
    """Walk the response line by line, peel out each labeled section.

    Returns (topic_a, topic_b, domain, winning, opinion, reasons). DOMAIN
    is still tolerated for backwards compatibility -- if the model emits
    it instead of TOPIC_A/TOPIC_B, we keep it as `domain`. New responses
    should populate TOPIC_A and TOPIC_B; old ones may not.
    """
    topic_a = ""
    topic_b = ""
    domain = ""
    winning: VideoSlot | None = None
    opinion_lines: list[str] = []
    reasons: list[str] = []

    section: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        m = _LABEL_RE.match(line)
        label = m.group(1).upper() if m else None
        rest = m.group(2).strip() if m else ""

        if label == "TOPIC_A":
            section = None
            topic_a = rest
            continue
        if label == "TOPIC_B":
            section = None
            topic_b = rest
            continue
        if label == "DOMAIN":
            section = None
            domain = rest
            continue
        if label == "WINNING_VIDEO":
            section = None
            v = rest.strip().strip(".").upper()
            if v.startswith("A"):
                winning = "A"
            elif v.startswith("B"):
                winning = "B"
            else:
                winning = None
            continue
        if label == "OPINION":
            section = "OPINION"
            if rest:
                opinion_lines.append(rest)
            continue
        if label == "REASONS":
            section = "REASONS"
            continue

        if section == "OPINION":
            stripped = line.strip()
            if stripped:
                opinion_lines.append(stripped)
        elif section == "REASONS":
            stripped = line.strip().lstrip("-*•").strip()
            if stripped:
                reasons.append(stripped[:200])
                if len(reasons) >= 4:
                    section = None  # cap

    return (
        topic_a.strip(),
        topic_b.strip(),
        domain.strip(),
        winning,
        " ".join(opinion_lines).strip(),
        reasons[:3],
    )


# ---------- Web-source extraction (same shape as routes/chat.py) ----------


def _extract_web_sources(message) -> list[WebSource]:
    if message is None:
        return []
    md = getattr(message, "response_metadata", None) or {}
    addl = getattr(message, "additional_kwargs", None) or {}
    gm = md.get("grounding_metadata") or addl.get("grounding_metadata")
    if not gm:
        return []
    if isinstance(gm, dict):
        chunks = gm.get("grounding_chunks") or gm.get("groundingChunks") or []
    else:
        chunks = getattr(gm, "grounding_chunks", None) or []
    out: list[WebSource] = []
    for c in chunks:
        web = c.get("web") if isinstance(c, dict) else getattr(c, "web", None)
        if not web:
            continue
        if isinstance(web, dict):
            uri = web.get("uri") or web.get("url")
            title = web.get("title") or ""
        else:
            uri = getattr(web, "uri", None) or getattr(web, "url", None)
            title = getattr(web, "title", "") or ""
        if uri:
            out.append(WebSource(url=uri, title=title or "", snippet=""))
    return out


# ---------- Public API ----------------------------------------------------


def get_cached(session_id: str) -> Verdict | None:
    with _lock:
        return _cache.get(session_id)


def clear(session_id: str) -> None:
    with _lock:
        _cache.pop(session_id, None)


# Time-sensitive topic markers — if any appears in metadata, we use the
# grounded model so the verdict can cite current world context. Otherwise
# we skip the search tool entirely (10-15s faster TTFT).
_TIME_SENSITIVE_KEYWORDS = (
    "election", "politics", "polic", "ceasefire", "war", "sanction",
    "exam", "result", "neet", "jee", "admission",
    "market", "stock", "crypto", "ipo", "rate cut", "inflation",
    "sport", "match", "tournament", "league", "transfer",
    "outbreak", "vaccine", "pandemic", "virus",
    "launch", "release", "announce",
)


def _looks_time_sensitive(meta_a: VideoMeta, meta_b: VideoMeta) -> bool:
    haystack = " ".join([
        meta_a.title or "",
        " ".join(meta_a.hashtags or []),
        " ".join(meta_a.topic_keywords or []),
        meta_b.title or "",
        " ".join(meta_b.hashtags or []),
        " ".join(meta_b.topic_keywords or []),
    ]).lower()
    return any(k in haystack for k in _TIME_SENSITIVE_KEYWORDS)


async def build_verdict_streaming(
    meta_a: VideoMeta,
    meta_b: VideoMeta,
    hook_a: str = "",
    hook_b: str = "",
):
    """Streaming variant: yields raw token chunks as the model writes,
    then yields a final ('done', Verdict) tuple.

    Grounding (Google Search) adds 10-15s of TTFT because the model decides
    whether to search BEFORE writing the first token. We skip grounding for
    evergreen topics (productivity, cooking, tutorials) and only enable it
    when the metadata suggests a time-sensitive topic.
    """
    # thinking_budget=0 disables the model's internal reasoning tokens,
    # cutting TTFT from 15-25s to 1-3s on flash-lite. We don't need extended
    # reasoning for a structured comparison verdict — the prompt itself is
    # the reasoning frame.
    # Grounding also disabled: adds 10-15s and the user can get current
    # context via the chat (which uses grounding when truly needed).
    try:
        llm = ChatGoogleGenerativeAI(
            model=settings.gemini_model,
            google_api_key=settings.google_api_key,
            temperature=0.4,
            max_output_tokens=512,
            thinking_budget=0,
        )
    except Exception:
        # Older langchain-google-genai versions don't accept thinking_budget.
        llm = ChatGoogleGenerativeAI(
            model=settings.gemini_model,
            google_api_key=settings.google_api_key,
            temperature=0.4,
            max_output_tokens=512,
        )
    model_call = llm
    use_grounding = False
    log.info("verdict streaming: thinking=0, grounding=off")

    accumulated = None
    text_parts: list[str] = []
    async for chunk in model_call.astream([
        SystemMessage(content=_SYSTEM),
        HumanMessage(content=_build_user_prompt(meta_a, meta_b, hook_a, hook_b)),
    ]):
        accumulated = chunk if accumulated is None else accumulated + chunk
        content = getattr(chunk, "content", "") or ""
        if isinstance(content, list):
            content = "".join(
                p.get("text", "") if isinstance(p, dict) else str(p) for p in content
            )
        if content:
            text_parts.append(content)
            yield ("token", content)

    full_text = "".join(text_parts)
    topic_a, topic_b, domain, winning, opinion, reasons = _parse_response(full_text)
    sources = _extract_web_sources(accumulated) if use_grounding else []
    verdict = Verdict(
        topic_a=topic_a, topic_b=topic_b, domain=domain,
        winning_video=winning, opinion=opinion or "(no opinion)",
        reasons=reasons, web_sources=sources, used_search=bool(sources),
    )
    yield ("done", verdict)


async def build_verdict(session_id: str, force: bool = False) -> Verdict:
    """Generate (or fetch from cache) the per-session verdict."""
    if not force:
        cached = get_cached(session_id)
        if cached is not None:
            return cached

    found = sessions.get(session_id)
    if not found:
        raise ValueError(f"session {session_id!r} not found")
    meta_a, meta_b = found["A"], found["B"]
    hook_a = _hook_text(session_id, "A")
    hook_b = _hook_text(session_id, "B")

    llm = ChatGoogleGenerativeAI(
        model=settings.gemini_model,
        google_api_key=settings.google_api_key,
        temperature=0.4,
        max_output_tokens=1024,
    )
    grounded = llm.bind_tools([{"google_search": {}}])

    msg = await grounded.ainvoke([
        SystemMessage(content=_SYSTEM),
        HumanMessage(content=_build_user_prompt(meta_a, meta_b, hook_a, hook_b)),
    ])
    text = msg.content if isinstance(msg.content, str) else "".join(
        p.get("text", "") if isinstance(p, dict) else str(p)
        for p in (msg.content or [])
    )

    topic_a, topic_b, domain, winning, opinion, reasons = _parse_response(text)
    sources = _extract_web_sources(msg)

    verdict = Verdict(
        topic_a=topic_a,
        topic_b=topic_b,
        domain=domain,
        winning_video=winning,
        opinion=opinion or "(no opinion)",
        reasons=reasons,
        web_sources=sources,
        used_search=bool(sources),
    )
    with _lock:
        _cache[session_id] = verdict
    log.info(
        "verdict session=%s winning=%s topics=(%r,%r) reasons=%d sources=%d",
        session_id, winning, topic_a, topic_b, len(reasons), len(sources),
    )
    return verdict
